### ISSUE TITLE
Fetching Selected id

### ISSUE THREAD

**Issue by elvisgn** [devslane/entity_state#1]
Hi,
Does the 'getId' method provide the selected item in a list ?

Is it possible to create filters and sorting selectors ?

Kindly share a full example of how to integrate into reducers...

**Comment by kush3107** [comment]
Hi @elvisgn , I am planning to add the sorting selectors but it is not present at the moment. Also `getId` does not get you the selected item in the list. The only purpose of the `getId` method is to get the unique identifier of the entity that you want to keep in the store. As mentioned in the docs. If you have any doubts please add a piece of code here and I can have a look.

**Comment by kush3107** [comment]
Hi @elvisgn , I have added a example project in the repo that demonstrates the basic usage of `entity_state` with flutter redux. Here is the link to reducer file - https://github.com/devslane/entity_state/blob/master/example/lib/reducers/user_reducer.dart

I think this should should solve your queries, I am closing the issue. Thanks. :)
